name: discord_bot

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pandas=1.1.3

  - jupyterlab=3.6.3
  - ipywidgets=8.0.6
  - pytest=7.2.2
  - pytest-cov
  - pluggy=1.0.0 #pytest dependency
  - iniconfig=2.0.0 #pytest dependency
  - tqdm=4.64.0
  - openpyxl=3.1.2
  - django=4.2.8

  - pip:
    - discord.py[voice]
    - python-dotenv
    - tzlocal
